### ISSUE TITLE
npx hardhat gobind 

### ISSUE THREAD

**Issue by senthilbalablockchain** [dl-solarity/hardhat-gobind#14]
I get this error when I do ` npx hardhat gobind`

`TypeError: Cannot set property crypto of #<Object> which has only a getter`

**Comment by jlvandenhout** [comment]
I can reproduce this by initializing the default Typescript Hardhat project using `yarn hardhat init`, adding the `hardhat-gobind` plugin as described and running `yarn hardhat compile`.

Node v20.8.0
Yarn v4.1.0
Hardhat v2.20.0
@solarity/hardhat-gobind v1.1.1

```shell
$ yarn hardhat compile
An unexpected error occurred:

TypeError: Cannot set property crypto of #<Object> which has only a getter
    at Object.<anonymous> (/home/develop/mre/gobind/node_modules/@solarity/hardhat-gobind/src/abigen/wasm/wasm_exec_node.js:17:18)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Object.require.extensions.<computed> [as .js] (/home/develop/mre/gobind/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Function.Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/home/develop/mre/gobind/node_modules/@solarity/hardhat-gobind/src/abigen/generator.js:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
```
